import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export const metadata = {
  // Open Graph (Untuk semua platform seperti WhatsApp, Facebook, LinkedIn)
  openGraph: {
    title: 'Rizky Oktan | Tech Enthusiast & Developer',
    description: 'Portfolio Rizky Oktan, seorang tech enthusiast dengan keahlian di bidang Full Stack Development, AI, dan Web3.',
    url: 'https://rizkyoktan.my.id',
    siteName: 'Rizky Oktan Portfolio',
    images: [
      {
        url: 'https://rizkyoktan.my.id/images/image-preview.png', // Ganti dengan URL gambar Anda
        width: 1200,
        height: 630,
        alt: 'Tampilan website portfolio Rizky Oktan',
      },
    ],
    locale: 'id_ID',
    type: 'website',
  },

  // Twitter Cards (Khusus untuk Twitter/X)
  twitter: {
    card: 'summary_large_image',
    title: 'Rizky Oktan | Developer & AI Specialist',
    description: 'Jelajahi portofolio Rizky Oktan, seorang pengembang yang fokus pada teknologi MERN, AI, dan Web3. Dibuat dengan Next.js dan Tailwind CSS.',
    images: ['https://rizkyoktan.my.id/images/image-preview.png'], // Ganti dengan URL gambar Anda
  },

  // Metadata dasar (untuk SEO)
  title: 'Rizky Oktan | Personal Portfolio',
  description: 'Portfolio Rizky Oktan, seorang pengembang full-stack dengan spesialisasi MERN, AI, dan Web3. Temukan proyek-proyek dan keahliannya di sini.',
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
